language: ruby

rvm:
- 2.1.5

sudo: false

addons:
  postgresql: "9.3"
  code_climate:
      repo_token:
        secure: "ai6+gVEZwIp5NUkV4c6WEQ6xGpsQ8jtaXlMST9Yxoptx+PiU4U2IyBrPiuYQfBnCBHfHSSrFe0doGgQiWFDmUX2MlEvXRajoGupFhk+xNcMS1jdLN7K+ktfWenNmyQtCTVx+cLT05uhNrHI2NwxpObFMSR2iPVxtqswROGra5YA="

before_script:
  - cp config/database.yml.travis config/database.yml
  - psql -c 'create database travis_ci_test;' -U postgres

notifications:
  slack:
    secure: "QaNl/iAYVGEFz2zveWr6rSxH/VHUj/hqWGYJw0isjHQI4XPQIaNSe8wO3F5AXVADMa2/0Wf7ffGZJUpSciF06q/QAdzEV/fznIWX5p65piD/JoDjuCI/qvGmdzExZbWZVFmETF0mXrF77AsEk9ei/8Fv+UerHMSaJpn5LzHzzoE="

script:
- bundle exec rspec
- bundle exec rubocop

deploy:
  provider: heroku
  api_key:
    secure: "ZDWFn6pTVtqg4DwXu0ge5wkFu8pVJV3c0px0KAXubOr8H0VNa4j1pOocS7JiCOAfsU1GVm1idyvCPS5Dyz5HqnZIqGYKS0TSiK4ezA10a1nb3MTPEiCtAyb6c/wxwPrtQ+7EvbI5oL7bWtXXhWXo7czNMG22+IhsQw3FPEnOxVQ="
  app: jellyfish-core-dev
  run:
    - "rake db:schema:load"
    - "rake"
    - "rake db:seed"
    - "rake sample:demo"